import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  String _selectedLanguage = 'Türkçe';

  String get selectedLanguage => _selectedLanguage;

  void changeLanguage(String newLanguage) {
    _selectedLanguage = newLanguage;
    notifyListeners();
  }
  String getLocalizedString(String key) {
    // Burada metinleri dil seçimine göre döndürün
    final translations = {
      'Türkçe': {
        'greeting': 'Merhaba, ',
        'profile': 'Profil',
        'maintenanceHistory': 'Bakım Geçmişi',
        'errorRecords': 'Hata Kayıtları',
        'documents': 'Belgeler',
        'settings': 'Ayarlar',
        'logout': 'Çıkış Yap',
        'idLabel': 'ID',
        'maintenanceDateLabel': 'Bakım Tarihi',
        "faulty": "Hatalı",
        'guide': 'Kılavuz',
        'kvkk_policy': 'KVKK Politikası',
        'privacy_policy': 'Gizlilik Politikası',
        'data_destruction': 'Veri Saklama ve İmha',
        'user_manual': 'Kullanma Kılavuzu',
        'kvkk': 'KVKK',
        'privacy': 'Gizlilik Politikası',
        'data_destruction_title': 'Veri Saklama ve İmha Politikası',
        'fill_all_fields': 'Lütfen tüm alanları doldurun.',
        'profile_updated_successfully': 'Profil başarıyla güncellendi.',
        'profile_update_failed': 'Profil güncelleme hatası:',
        'password_changed_successfully': 'Parola başarıyla güncellendi.',
        'password_change_failed': 'Parola güncelleme başarısız oldu:',
        'login_required': 'Lütfen oturum açın.',
        'edit': 'Düzenle',
        'name': 'İsim Soyisim',
        'email': 'Mail',
        'username': 'Kullanıcı Adı',
        'save': 'Kaydet',
        'cancel': 'İptal',
        'change_password': 'Parola Değiştir',
        'new_password': 'Yeni Parola',
        'error_registering_user': 'Kullanıcı kaydedilirken bir hata oluştu',
        'error': 'Hata',
        'ok': 'Tamam',
        'password': 'Şifre',
        'complete_registration': 'Kaydı Tamamla',
        'editUser': 'Kullanıcıyı Düzenle',
        'addSubUser': 'Alt Kullanıcı Ekle',
        'role': 'Rol',
        'add': 'Ekle',
        'engineer': 'Mühendis',
        'technician': 'Teknisyen',
        'users': 'Kullanıcılar',
        'noSubUsersFound': 'Kayıtlı alt kullanıcı bulunamadı',
        'noName': 'İsim Yok',
        'noRole': 'Rol Yok',
        'category': 'Kategori',
        'functionsAndControl': 'Fonksiyonlar ve Kontrol',
        'platformAssembly': 'Platform Montaj',
        'scissors': 'Makaslar',
        'general': 'Genel',
        'hydraulics': 'Hidrolik',
        'electric': 'Elektrik',
        'guideAndLabel': 'Kılavuz ve Etiket',
        'chassis': 'Şase',
        'unknownCategory': 'Bilinmeyen Kategori',
        'complete': 'Tamam',
        'enterNote': 'Not Girin',
        'invalidIndex': 'Geçersiz indeks',
        'invalid': 'Geçersiz',
        'delete': 'Sil',
        'maintenanceDetails': 'Bakım Detayları',
        'maintenanceID': 'Bakım ID',
        'maintenanceDate': 'Bakım Tarihi',
        'controls': 'Kontroller',
        'notes': 'Notlar',
        'Fonksiyonlar ve Kontrol': 'Fonksiyonlar ve Kontrol',
        'Platform Montaj': 'Platform Montaj',
        'Makaslar': 'Makaslar',
        'Genel': 'Genel',
        'Hidrolik': 'Hidrolik',
        'Elektrik': 'Elektrik',
        'Kılavuz ve Etiket': 'Kılavuz ve Etiket',
        'Şase': 'Şase',
        'Bilinmeyen Kategori': 'Bilinmeyen Kategori',
      },
      'İngilizce': {
        'greeting': 'Hello, ',
        'profile': 'Profile',
        'maintenanceHistory': 'Maintenance History',
        'errorRecords': 'Error Records',
        'documents': 'Documents',
        'settings': 'Settings',
        'logout': 'Logout',
        'idLabel': 'ID',
        'maintenanceDateLabel': 'Maintenance Date',
        "faulty": "Faulty",
        'guide': 'Guide',
        'kvkk_policy': 'KVKK Policy',
        'privacy_policy': 'Privacy Policy',
        'data_destruction': 'Data Retention and Destruction',
        'user_manual': 'User Manual',
        'kvkk': 'KVKK',
        'privacy': 'Privacy',
        'data_destruction_title': 'Data Retention and Destruction Policy',
        'fill_all_fields': 'Please fill in all fields.',
        'profile_updated_successfully': 'Profile updated successfully.',
        'profile_update_failed': 'Failed to update profile:',
        'password_changed_successfully': 'Password changed successfully.',
        'password_change_failed': 'Failed to change password:',
        'login_required': 'Please log in.',
        'edit': 'Edit',
        'name': 'Name Surname',
        'email': 'E-mail',
        'username': 'Username',
        'save': 'Save',
        'cancel': 'Cancel',
        'change_password': 'Change Password',
        'new_password': 'New Password',
        'error_registering_user': 'An error occurred while registering the user',
        'error': 'Error',
        'ok': 'OK',
        'password': 'Password',
        'complete_registration': 'Complete Registration',
        'editUser': 'Edit User',
        'addSubUser': 'Add Sub User',
        'role': 'Role',
        'add': 'Add',
        'engineer': 'Engineer',
        'technician': 'Technician',
        'users': 'Users',
        'noSubUsersFound': 'No sub-users found',
        'noName': 'No Name',
        'noRole': 'No Role',
        'category': 'Category',
        'functionsAndControl': 'Functions and Control',
        'platformAssembly': 'Platform Assembly',
        'scissors': 'Scissors',
        'general': 'General',
        'hydraulics': 'Hydraulics',
        'electric': 'Electric',
        'guideAndLabel': 'Guide and Label',
        'chassis': 'Chassis',
        'unknownCategory': 'Unknown Category',
        'complete': 'Complete',
        'enterNote': 'Enter Note',
        'invalidIndex': 'Invalid Index',
        'invalid': 'Invalid',
        'delete': 'Delete',
        'maintenanceDetails': 'Maintenance Details',
        'maintenanceID': 'Maintenance ID',
        'maintenanceDate': 'Maintenance Date',
        'controls': 'Controls',
        'notes': 'Notes',
        'Fonksiyonlar ve Kontrol': 'Functions and Control',
        'Platform Montaj': 'Platform Assembly',
        'Makaslar': 'Scissors',
        'Genel': 'General',
        'Hidrolik': 'Hydraulic',
        'Elektrik': 'Electric',
        'Kılavuz ve Etiket': 'Guide and Label',
        'Şase': 'Chassis',
        'Bilinmeyen Kategori': 'Unknown Category',
      },
    };

    return translations[_selectedLanguage]?[key] ?? key;
  }
}