library globals;

// Değişkenleri burada String olarak tanımlayın
String ownerUser = '';
String lastUpdate = '';
String machineType = '';
String machineID = '';
String devirmeYuruyusSecim = '';
String calismaSekli = '';
String emniyetCercevesi = '';
String yavaslamaLimit = '';
String altLimit = '';
String kapiTablaAcKonum = '';
String basincSalteri = '';
String kapiSecimler = '';
String kapiAcTipi = '';
String kapi1Tip = '';
String kapi1AcSure = '';
String kapi2Tip = '';
String kapi2AcSure = '';
String kapitablaTip = '';
String kapiTablaAcSure = '';
String yukariYavasLimit = '';
String devirmeYukariIleriLimit = '';
String devirmeAsagiGeriLimit = '';
String devirmeSilindirTipi = '';
String platformSilindirTipi = '';
String yukariValfTmr = '';
String asagiValfTmr = '';
String devirmeYukariIleriTmr = '';
String devirmeAsagiGeriTmr = '';
String makineCalismaTmr = '';
String buzzer = '';
String demoMode = '';
String calismaSayisi1 = '';
String calismaSayisi10 = '';
String calismaSayisi100 = '';
String calismaSayisi10000 = '';
String dilSecim = '';
String eepromData38 = '';
String eepromData39 = '';
String eepromData40 = '';
String eepromData41 = '';
String eepromData42 = '';
String eepromData43 = '';
String eepromData44 = '';
String eepromData45 = '';
String eepromData46 = '';
String eepromData47 = '';
String lcdBacklightSure = '';


